### PR TITLE
Fix example and make echo canceller adjust delay dynamically

### PR DESCRIPTION
**Pull request by mannol**
I also removed the open AL example as it's useless.

### CODE REVIEW

**Comment by nurupo** [comment]
What do you mean by "useless"? Most Tox clients use OpenAL, so it would be nice to also have OpenAL example.

**Comment by nurupo** [comment]
Also, your commit message doesn't say what exactly did you fix, i.e. what was wrong with the existing example.

**Comment by mannol** [comment]
The reason for removal was that it didn't show how exactly filter_audio should be used. The most essential step was skipped: setting echo delay. The reason I removed it instead of fixing it was that
I don't know how to get IO latency from openAL api. Ideally, all clients should drop openAL or find a way to get that information without openAL.

**Comment by nurupo** [comment]
Looks like there is a way to get input latency in OpenAL http://kcat.strangesoft.net/openal-extensions/SOFT_source_latency.txt

You can also email the OpenAL author or catch him in #openal on freenode, he is very responsive, I have emailed him before.

Also, don't forget that OpenAL abstracts like 10 different audio backends of Linux, OS X and Windows, saying `Ideally, all clients should drop openAL` is kind of harsh on client developers : )

**Comment by mannol** [comment]
Oh, an extension. That and a need for modified version of open AL (for getting current output) alone makes it harder for client developers (and maintainers).

**Comment by nurupo** [comment]
This is an extension of the OpenAL specification, it's not a separate OpenALSoft extension (i.e. module, plugin) that you need to compile and maintain, it should already work out of the box [as it's part of the main codebase](https://github.com/kcat/openal-soft/search?utf8=%E2%9C%93&q=AL_SEC_OFFSET_LATENCY_SOFT).

**Comment by nurupo** [comment]
Also, the spec I linked to says

>delay between where the AL is processing and what is actually being heard

so I think this **is** the output latency, unless I'm misunderstanding things. It's a bit confusing as the file is named "source_latency".

**Comment by mannol** [comment]
Neat. I believe source is often used term for IO (or just one of those).

**Comment by nurupo** [comment]
@mannol any progress making the example work with OpenALSoft using the source latency information it provides?

**Comment by mannol** [comment]
@nurupo nope. I tried hard but it's impossible to do it with openal.

**Comment by nurupo** [comment]
Anything specific as to why it's impossible? Is the source latency information incorrect?

**Comment by mannol** [comment]
Yes, the source latency information provided is irrelevant as it provides no information about how much time it takes for an audio signal to reach from output to input. Even if we had that information the open Al makes it impossible to apply echo filters because of the queueing inside it is very hard to compare with a sample signal.

With portaudio, the queueing is done at a higher level (by the app) and the latency information that is provided is the exact one needed for the echo filter to be applied correctly. It's really the only audio engine I've found so far that's capable of echo cancellation.

**Comment by mannol** [comment]
@irungentoo as responsive as always I see... Thanks!

**Comment by nurupo** [comment]
Cool, will trigger the filter_audio job on Jenkins then.

**Pull request merged**
