### PR TITLE
Fixed sed -i option to be compatible with BSD sed.

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by Ansa89** [comment]
This will break compatibility with my sed (4.2.1) and possibly with OSX sed (cannot test it).

**Comment by yurivict** [comment]
Why? -i'' should be the same as -i '' everywhere.

**Comment by yurivict** [comment]
How about now?

**Comment by yurivict** [comment]
FYI this holds up BSD port update for qTox.

**Comment by Ansa89** [comment]
Isn't `LIBDIR` already defined as "lib" at the beginning of makefile?

**Comment by yurivict** [comment]
Yes, Makefile has LIBDIR?=lib in the beginning.
But for some reason that I don't know it evaluates to /usr/lib on BSD. So LIBDIR=lib actually prevents the build problem on BSD, and LIBDIR?=lib works ok on other OSes.

**Comment by Ansa89** [comment]
Ok, I merged it: Ansa89//filter_audio@25a6db64a4f2b231785086243f422574eeab1f68.

**Comment by yurivict** [comment]
Are you going to merge it here, under irungentoo/ ? Because this is the master copy (or is it?) and I can only reference the master project for the BSD port.

**Comment by Ansa89** [comment]
>Are you going to merge it here?

irungentoo/filter_audio#15

**Pull request merged**
