### PR TITLE
Combined pull requests

### PR DESCRIPTION
**Pull request by ReDetection**
This combines #9, #10 and #11 as @irungentoo asked in IRC.

@Ansa89, @novist, please check if everything is working fine in your environment

### CODE REVIEW

**Comment by novist** [comment]
on mingw32 i get following error:

	  LD    libfilteraudio.dll
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x47): undefined reference to `WebRtcAec_CreateAec'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x122): undefined reference to `WebRtcAec_FreeAec'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x1ca): undefined reference to `WebRtcAec_InitAec'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x2fd): undefined reference to `WebRtcAec_reported_delay_enabled'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x4d6): undefined reference to `WebRtcAec_system_delay'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x4ef): undefined reference to `WebRtcAec_SetSystemDelay'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x551): undefined reference to `WebRtcAec_BufferFarendPartition'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x698): undefined reference to `WebRtcAec_delay_correction_enabled'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x82b): undefined reference to `WebRtcAec_SetConfigCore'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x889): undefined reference to `WebRtcAec_echo_state'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x923): undefined reference to `WebRtcAec_GetEchoStats'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0xcb4): undefined reference to `WebRtcAec_GetDelayMetricsCore'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x108d): undefined reference to `WebRtcAec_system_delay'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x10d4): undefined reference to `WebRtcAec_MoveFarReadPtr'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x10f6): undefined reference to `WebRtcAec_reported_delay_enabled'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x118f): undefined reference to `WebRtcAec_ProcessFrame'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x12b1): undefined reference to `WebRtcAec_system_delay'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x12f9): undefined reference to `WebRtcAec_MoveFarReadPtr'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x1311): undefined reference to `WebRtcAec_reported_delay_enabled'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x13ba): undefined reference to `WebRtcAec_ProcessFrame'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x1402): undefined reference to `WebRtcAec_system_delay'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x145e): undefined reference to `WebRtcAec_MoveFarReadPtr'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x15c0): undefined reference to `WebRtcAec_system_delay'
	aec/echo_cancellation.o:echo_cancellation.c:(.text+0x161c): undefined reference to `WebRtcAec_MoveFarReadPtr'
	c:/Qt/Qt5.4.0/Tools/mingw491_32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: aec/echo_cancellation.o: bad reloc address 0x20 in section `.eh_frame'
	collect2.exe: error: ld returned 1 exit status
	make: *** [libfilteraudio.dll] Error 1

**Comment by ReDetection** [comment]
Did you `make clean` before `make`?

**Comment by novist** [comment]
Actually i removed entire source tree and checked out again from github. So its as ``yes`` as it gets ;)

**Comment by ReDetection** [comment]
Hmm, I need to investigate it some more

**Pull request merged**
